# Generated by Django 5.2 on 2025-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='access',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
